[project]
name = "flask-websocket-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-socketio>=5.4.1",
    "flask>=3.1.0",
]
